# the old: usr/bin/timed
usr/bin/timed

# compiled in, don't install
# usr/share/timed/typeinfo

usr/share/contextkit/providers/com.nokia.time.context

# backup framework
usr/share/backup-framework/applications/timedbackup.conf
usr/share/backup-framework/scripts

# moved to tzdata:
# usr/share/zoneinfo
# usr/share/tzdata-timed

# halt timed and clear cache directory
/etc/osso-cud-scripts
/etc/osso-rfs-scripts

# session bus address helper
usr/bin/timed-aegis-session-helper
